# Generated by Django 4.2.7 on 2023-11-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_managers_user_created_at_user_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
