# Generated by Django 4.2.7 on 2023-11-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='provider',
            field=models.CharField(choices=[('GOOGLE', 'GOOGLE'), ('COMMON', 'COMMON'), ('KAKAO', 'KAKAO')], default='COMMON', max_length=10),
        ),
    ]
