# Generated by Django 4.2.7 on 2023-12-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='provider',
            field=models.CharField(choices=[('GOOGLE', 'GOOGLE'), ('COMMON', 'COMMON'), ('KAKAO', 'KAKAO'), ('INSTAGRAM', 'INSTAGRAM')], default='COMMON', max_length=10),
        ),
    ]
